name: Build and Publish to Github Pages

on:
  push:
    branches:
      - master
      - draft

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "pelican[markdown]"
          
      - name: Generate site
        run: python -m pelican content
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: output
    
  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: website

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website